name: pr-check.yml
on:
  pull_request:
jobs:
  dev_to_master:
    name: Ensure master only has pull requests from develop
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1